version: "3"

services:
  math-server:
    build:
      context: ./servers/math_server
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: always

  weather-server:
    build:
      context: ./servers/weather_server
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    restart: always

  information-server:
    build:
      context: ./servers/process_server
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    restart: always
    privileged: true

  string-server:
    build:
      context: ./servers/string_server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
