version: "3"

services:
  math-server:
    build:
      context: ./servers/math_server
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - mcp-network
    restart: always

  weather-server:
    build:
      context: ./servers/weather_server
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - mcp-network
    restart: always

  process-server:
    build:
      context: ./servers/process_server
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    networks:
      - mcp-network
    restart: always
    privileged: true # Needed for full system access

  string-server:
    build:
      context: ./servers/string_server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - mcp-network
    restart: always

networks:
  mcp-network:
    driver: bridge
